service: merchant-onboarding-system

custom:
  merchantDetailsTableName: 'MERCHANT_DETAILS_${self:provider.stage}'

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - { "Fn::GetAtt": ["MerchantDetailsDynamoDBTable", "Arn" ] }
  environment:
    MERCHANTS_TABLE_NAME: ${self:custom.merchantDetailsTableName}

package:
  artifact: 'target/${self:service}-${self:provider.stage}.jar'

functions:
  listMerchants:
    handler: com.merchant.onboarding.handlers.ListOnboardedMerchantsHandler
    events:
      - http:
          path: /merchantslist
          method: get
  createMerchant:
    handler: com.merchant.onboarding.handlers.CreateMerchantRequestHandler
    events:
      - http:
          path: /merchants
          method: post

resources:
  Resources:
    MerchantDetailsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.merchantDetailsTableName}
        AttributeDefinitions:
          - AttributeName: merchantId
            AttributeType: S
          - AttributeName: merchantName
            AttributeType: S
        KeySchema:
          - AttributeName: merchantId
            KeyType: HASH
          - AttributeName: merchantName
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
