package com.merchant.onboarding.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;
import java.util.StringJoiner;

@DynamoDBTable(tableName = "PLACEHOLDER_MERCHANTS_TABLE_NAME")
public class Merchant {

    @DynamoDBHashKey(attributeName = "merchantId")
    @DynamoDBAutoGeneratedKey
    private String merchantId;
    @DynamoDBRangeKey(attributeName = "merchantName")
    private String merchantName;
    @DynamoDBAttribute(attributeName = "merchantShortName")
    private String merchantShortName;
    @DynamoDBAttribute(attributeName = "legalName")
    private String legalName;
    @DynamoDBAttribute(attributeName = "organizationName")
    private String organizationName;
    @DynamoDBAttribute(attributeName = "merchantBusinessType")
    private String merchantBusinessType;
    @DynamoDBAttribute(attributeName = "maxTransactionAmount")
    private long maximumTransactionAmount;
    @DynamoDBAttribute(attributeName = "country")
    private String country;
    @DynamoDBAttribute(attributeName = "state")
    private String state;
    @DynamoDBAttribute(attributeName = "city")
    private String city;
    @DynamoDBAttribute(attributeName = "streetAddress")
    private String streetAddress;
    @DynamoDBAttribute(attributeName = "streetAddress2")
    private String streetAddress2;
    @DynamoDBAttribute(attributeName = "zipCode")
    private long zipCode;
    @DynamoDBAttribute(attributeName = "email")
    private String emailAddress;
    @DynamoDBAttribute(attributeName = "phone")
    private String phone;
    @DynamoDBAttribute(attributeName = "fax")
    private String fax;
    @DynamoDBAttribute(attributeName = "merchantStatus")
    private String merchantStatus;
    @DynamoDBAttribute(attributeName = "activationDate")
    private Date activationDate;
    @DynamoDBAttribute(attributeName = "deactivationDate")
    private Date deactivationDate;
    @DynamoDBAttribute(attributeName = "website")
    private String website;
    @DynamoDBAttribute(attributeName = "createDate")
    private Date createDate;
    @DynamoDBAttribute(attributeName = "createdBy")
    private String createdBy;
    @DynamoDBAttribute(attributeName = "kycDocType")
    private String kycDocType;
    @DynamoDBAttribute(attributeName = "kycDocNumber")
    private String kycDocNumber;
    @DynamoDBAttribute(attributeName = "kycDocName")
    private String kycDocName;

    public String getMerchantId() {
        return this.merchantId;
    }
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    public String getOrganizationName() {
        return organizationName;
    }
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    public String getMerchantName() {
        return merchantName;
    }
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    public String getMerchantShortName() {
        return merchantShortName;
    }
    public void setMerchantShortName(String merchantShortName) {
        this.merchantShortName = merchantShortName;
    }

    public String getLegalName() {
        return legalName;
    }
    public void setLegalName(String legalName) {
        this.legalName = legalName;
    }

    public String getState() {
        return state;
    }
    public void setState(String state) {
        this.state = state;
    }

    public String getCountry() {
        return country;
    }
    public void setCountry(String country) {
        this.country = country;
    }

    public String getCity() {
        return city;
    }
    public void setCity(String city) {
        this.city = city;
    }

    public String getStreetAddress() {
        return streetAddress;
    }
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }

    public String getStreetAddress2() {
        return streetAddress2;
    }
    public void setStreetAddress2(String streetAddress2) {
        this.streetAddress2 = streetAddress2;
    }

    public long getZipCode() {
        return zipCode;
    }
    public void setZipCode(long zipCode) {
        this.zipCode = zipCode;
    }

    public String getEmailAddress() {
        return emailAddress;
    }
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getPhone() {
        return phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getFax() {
        return fax;
    }
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getMerchantBusinessType() {
        return merchantBusinessType;
    }
    public void setMerchantBusinessType(String merchantBusinessType) {
        this.merchantBusinessType = merchantBusinessType;
    }

    public long getMaximumTransactionAmount() {
        return maximumTransactionAmount;
    }
    public void setMaximumTransactionAmount(long maximumTransactionAmount) {
        this.maximumTransactionAmount = maximumTransactionAmount;
    }

    public String getMerchantStatus() {
        return merchantStatus;
    }
    public void setMerchantStatus(String merchantStatus) {
        this.merchantStatus = merchantStatus;
    }

    public Date getActivationDate() {
        return activationDate;
    }
    public void setActivationDate(Date activationDate) {
        this.activationDate = activationDate;
    }

    public Date getDeactivationDate() {
        return deactivationDate;
    }
    public void setDeactivationDate(Date deactivationDate) {
        this.deactivationDate = deactivationDate;
    }

    public String getWebsite() {
        return website;
    }
    public void setWebsite(String website) {
        this.website = website;
    }

    public Date getCreateDate() {
        return createDate;
    }
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getCreatedBy() {
        return createdBy;
    }
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getKycDocType() {
        return kycDocType;
    }
    public void setKycDocType(String kycDocType) {
        this.kycDocType = kycDocType;
    }

    public String getKycDocNumber() {
        return kycDocNumber;
    }
    public void setKycDocNumber(String kycDocNumber) {
        this.kycDocNumber = kycDocNumber;
    }

    public String getKycDocName() {
        return kycDocName;
    }
    public void setKycDocName(String kycDocName) {
        this.kycDocName = kycDocName;
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", Merchant.class.getSimpleName() + "[", "]")
                .add("merchantId='" + merchantId + "'")
                .add("merchantName='" + merchantName + "'")
                .add("merchantShortName='" + merchantShortName + "'")
                .add("legalName='" + legalName + "'")
                .add("organizationName='" + organizationName + "'")
                .add("merchantBusinessType='" + merchantBusinessType + "'")
                .add("maximumTransactionAmount=" + maximumTransactionAmount)
                .add("country='" + country + "'")
                .add("state='" + state + "'")
                .add("city='" + city + "'")
                .add("streetAddress='" + streetAddress + "'")
                .add("streetAddress2='" + streetAddress2 + "'")
                .add("zipCode=" + zipCode)
                .add("emailAddress='" + emailAddress + "'")
                .add("phone='" + phone + "'")
                .add("fax='" + fax + "'")
                .add("merchantStatus='" + merchantStatus + "'")
                .add("activationDate=" + activationDate)
                .add("deactivationDate=" + deactivationDate)
                .add("website='" + website + "'")
                .add("createDate=" + createDate)
                .add("createdBy='" + createdBy + "'")
                .add("kycDocType='" + kycDocType + "'")
                .add("kycDocNumber='" + kycDocNumber + "'")
                .add("kycDocName='" + kycDocName + "'")
                .toString();
    }
}
